// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderRespository;

namespace CapOderDemo.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20210804031046_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrderRespository.Models.OrderEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Count")
                        .HasColumnName("COUNT")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNo")
                        .HasColumnName("ORDER_NO")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProductName")
                        .HasColumnName("PRODUCT_NAME")
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.ToTable("TB_ORDER");

                    b.HasComment("订单表");
                });
#pragma warning restore 612, 618
        }
    }
}
